openapi: 3.0.0
info:
  title: Interest Rate Determination
  description: >+
    No toolkit to be used in IBM Business Automation Workflow has been created
    for RATECALC v1rate. You can enable that in the Solution Designer on API
    Namespace level.

  version: 1.0.0
servers:
  - url: 'https://qa-br.apps.openshift-03.knowis.cloud:443/RATECALC/api/v1rate'
security:
  - oauth2schema: []
paths:
  '/{duration}':
    get:
      tags: []
      operationId: getInterestRateByDuration
      parameters:
        - name: duration
          in: path
          description: |
            duration in months
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            description: |
              duration in months
        - name: Accept-Language
          in: header
          description: >-
            List of acceptable human languages for response. According to `RFC
            7231`
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: X-B3-ParentSpanId
          in: header
          description: Zipkin Parent Span Id (e.g. `6adc7f8b31f35e91`)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: X-B3-SpanId
          in: header
          description: Zipkin Span Id (e.g. `0a7b5cd9c2568f7d`)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: X-B3-TraceId
          in: header
          description: Zipkin Trace Id (e.g. `0a7b5cd9c2568f7d6adc7f8b31f35e91`)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: X-B3-Sampled
          in: header
          description: Zipkin Sampled (e.g. `0`)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: X-DEBUG-SESSION
          in: header
          description: X-DEBUG-SESSION
          required: false
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: >
            Determines the interest rate (nominal and effective) based on the
            duration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestRate'
components:
  schemas:
    InterestRate:
      type: object
      properties:
        effectiveInterestRate:
          type: number
        nominalInterestRate:
          type: number
  responses: {}
  parameters:
    Accept-Language:
      name: Accept-Language
      in: header
      description: List of acceptable human languages for response. According to `RFC 7231`
      required: false
      style: simple
      explode: false
      schema:
        type: string
    X-B3-ParentSpanId:
      name: X-B3-ParentSpanId
      in: header
      description: Zipkin Parent Span Id (e.g. `6adc7f8b31f35e91`)
      required: false
      style: simple
      explode: false
      schema:
        type: string
    X-B3-SpanId:
      name: X-B3-SpanId
      in: header
      description: Zipkin Span Id (e.g. `0a7b5cd9c2568f7d`)
      required: false
      style: simple
      explode: false
      schema:
        type: string
    X-B3-TraceId:
      name: X-B3-TraceId
      in: header
      description: Zipkin Trace Id (e.g. `0a7b5cd9c2568f7d6adc7f8b31f35e91`)
      required: false
      style: simple
      explode: false
      schema:
        type: string
    X-B3-Sampled:
      name: X-B3-Sampled
      in: header
      description: Zipkin Sampled (e.g. `0`)
      required: false
      style: simple
      explode: false
      schema:
        type: string
    X-DEBUG-SESSION:
      name: X-DEBUG-SESSION
      in: header
      description: X-DEBUG-SESSION
      required: false
      style: simple
      explode: false
      schema:
        type: string
  requestBodies: {}
  securitySchemes:
    oauth2schema:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: >-
            https://auth.apps.openshift-03.knowis.cloud/auth/realms/qa-br/protocol/openid-connect/auth
          scopes: {}
      x-tokenName: id_token
x-knowis-solutionAcronym: RATECALC
x-knowis-apiName: v1rate
x-knowis-namespacePrefix: v1rate
x-knowis-ibmBpmIntegration: false
